import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import Card from '../../components/common/Card';
import Button from '../../components/common/Button';
import FormField from '../../components/common/FormField';

const CdssAnalysis = () => {
  const { imageId } = useParams();
  const navigate = useNavigate();

  const [reviewStatus, setReviewStatus] = useState('pending');
  const [doctorNotes, setDoctorNotes] = useState('');

  const analysisData = {
    analysisId: 'CDSS001',
    imageId: imageId,
    analysisDate: '2025-12-05',
    findings: {
      additionalFindings: 'Slight ST-segment elevation detected in leads V2-V4. Possible early signs of myocardial infarction. Recommend immediate clinical correlation and further testing.'
    },
    confidenceScore: 0.87,
    reviewedBy: null,
    reviewStatus: reviewStatus
  };

  const handleReview = (status) => {
    setReviewStatus(status);
    console.log('Review status updated:', status, 'Notes:', doctorNotes);
    navigate('/radiology');
  };

  return (
    <div className="page-container">
      <div className="page-header">
        <h1>CDSS Analysis Results</h1>
        <div className="header-actions">
          <Button variant="secondary" onClick={() => navigate(-1)}>Back</Button>
          <Button onClick={() => navigate(`/radiology/${imageId}`)}>View Image</Button>
        </div>
      </div>

      <Card title="Analysis Information">
        <div className="info-grid">
          <div className="info-item">
            <label>Analysis ID:</label>
            <span>{analysisData.analysisId}</span>
          </div>
          <div className="info-item">
            <label>Image ID:</label>
            <span>{analysisData.imageId}</span>
          </div>
          <div className="info-item">
            <label>Analysis Date:</label>
            <span>{analysisData.analysisDate}</span>
          </div>
          <div className="info-item">
            <label>Confidence Score:</label>
            <span className="confidence-score">
              {(analysisData.confidenceScore * 100).toFixed(0)}%
              <div className="confidence-bar">
                <div 
                  className="confidence-fill" 
                  style={{ width: `${analysisData.confidenceScore * 100}%` }}
                />
              </div>
            </span>
          </div>
          <div className="info-item">
            <label>Review Status:</label>
            <span className={`status status-${analysisData.reviewStatus}`}>
              {analysisData.reviewStatus}
            </span>
          </div>
        </div>
      </Card>

      <Card title="AI-Generated Findings">
        <div className="findings-section">
          <div className="finding-item">
            <h4>Clinical Findings:</h4>
            <p className="finding-text">{analysisData.findings.additionalFindings}</p>
          </div>

          <div className="ai-disclaimer">
            <strong>⚠️ Important Notice:</strong>
            <p>
              This analysis is generated by an AI-powered Clinical Decision Support System (CDSS). 
              All findings must be reviewed and validated by a qualified physician before making 
              any clinical decisions.
            </p>
          </div>
        </div>
      </Card>

      <Card title="Doctor Review">
        <FormField
          label="Review Notes"
          type="textarea"
          value={doctorNotes}
          onChange={(e) => setDoctorNotes(e.target.value)}
          placeholder="Enter your review notes and clinical correlation..."
        />

        <div className="review-actions">
          <Button variant="success" onClick={() => handleReview('approved')}>
            Approve Analysis
          </Button>
          <Button variant="warning" onClick={() => handleReview('modified')}>
            Approve with Modifications
          </Button>
          <Button variant="danger" onClick={() => handleReview('rejected')}>
            Reject Analysis
          </Button>
        </div>
      </Card>

      <Card title="Recommendations">
        <ul className="recommendations-list">
          <li>Immediate clinical correlation recommended</li>
          <li>Consider ordering cardiac enzymes (Troponin levels)</li>
          <li>Monitor patient for chest pain and vital signs</li>
          <li>Follow-up ECG in 6 hours</li>
          <li>Consult with cardiology specialist if symptoms persist</li>
        </ul>
      </Card>
    </div>
  );
};

export default CdssAnalysis;
